name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Update package version
      run: |
        npm version ${{ steps.extract_version.outputs.version }} --no-git-tag-version
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run lint
      run: npm run lint
      
    - name: Build project
      run: npm run build
      
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create Pull Request for version update
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: bump version to ${{ steps.extract_version.outputs.version }}'
        title: 'chore: bump version to ${{ steps.extract_version.outputs.version }}'
        body: |
          ## 🚀 Version Bump
          
          This PR updates the package version to `${{ steps.extract_version.outputs.version }}`.
          
          ### Changes
          - Updated `package.json` version
          - Updated `package-lock.json`
          
          ### Release Status
          - ✅ Published to npm: [staging-coordinator@${{ steps.extract_version.outputs.version }}](https://www.npmjs.com/package/staging-coordinator/v/${{ steps.extract_version.outputs.version }})
          - 🏷️ Git tag: `v${{ steps.extract_version.outputs.version }}`
          
          Auto-generated by release workflow.
        branch: version-bump-${{ steps.extract_version.outputs.version }}
        delete-branch: true
        base: main
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.extract_version.outputs.version }}
        name: v${{ steps.extract_version.outputs.version }}
        body: |
          ## 🎉 Release v${{ steps.extract_version.outputs.version }}
          
          ### Installation
          ```bash
          npm install -g staging-coordinator@${{ steps.extract_version.outputs.version }}
          ```
          
          ### Usage
          ```bash
          staging-coordinator <product-name> <environment-name>
          ```
          
          ### What's Changed
          See the [full changelog](https://github.com/${{ github.repository }}/compare/v${{ steps.extract_version.outputs.version }}...HEAD) for details.
          
          ---
          📦 [npm package](https://www.npmjs.com/package/staging-coordinator/v/${{ steps.extract_version.outputs.version }})
          📖 [Documentation](https://github.com/${{ github.repository }}/blob/main/README.md)
        draft: false
        prerelease: false
